# Generated by Django 5.1.1 on 2024-09-19 12:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="documents/",
            ),
        ),
    ]
